import type {
  AuditEvent,
  AuthUser,
  DashboardSnapshot,
  Employee,
  ManagedUser,
  PermissionCatalog,
  WorkLog,
} from "./api";

export interface MockUserSession {
  user: AuthUser;
  capabilities: string[];
}

export const TEST_USERS: Record<string, { password: string; session: MockUserSession }> = {
  "admin@nairobi.go.ke": {
    password: "Admin@Nairobi2026!Ops",
    session: {
      user: {
        id: "user_admin_01",
        email: "admin@nairobi.go.ke",
        displayName: "Nairobi System Administrator",
        mustChangePassword: false,
        assignments: [
          {
            id: "asgn_admin_01",
            role: "SYSTEM_ADMIN",
            roleName: "System Administrator",
            scopeType: "COUNTY",
            countyId: "county_nairobi",
            subcountyId: null,
            wardId: null,
          },
        ],
      },
      capabilities: [
        "STAFF_READ",
        "STAFF_MANAGE",
        "STAFF_IMPORT",
        "ATTENDANCE_READ",
        "ATTENDANCE_MANAGE",
        "WORK_READ",
        "WORK_CREATE",
        "WORK_REVIEW",
        "ABSENCE_READ",
        "ABSENCE_MANAGE",
        "ABSENCE_REVIEW",
        "MEDICAL_READ",
        "REPORTS_READ",
        "REPORTS_GENERATE",
        "REPORTS_EXPORT",
        "REPORTS_FINALIZE",
        "AUDIT_READ",
        "USERS_MANAGE",
        "USERS_READ",
        "USERS_DISABLE",
        "PERMISSIONS_MANAGE",
        "SCOPE_MANAGE",
        "RECORD_ARCHIVE",
        "EVIDENCE_REMOVE",
      ],
    },
  },
  "ward.officer@nairobi.go.ke": {
    password: "Officer@Makina2026!Ops",
    session: {
      user: {
        id: "user_ward_01",
        email: "ward.officer@nairobi.go.ke",
        displayName: "Makina Ward Environment Officer",
        mustChangePassword: false,
        assignments: [
          {
            id: "asgn_ward_01",
            role: "WARD_OFFICER",
            roleName: "Ward Environment Officer",
            scopeType: "WARD",
            countyId: "county_nairobi",
            subcountyId: "subcounty_kibra",
            wardId: "ward_makina",
          },
        ],
      },
      capabilities: [
        "STAFF_READ",
        "STAFF_MANAGE",
        "STAFF_IMPORT",
        "ATTENDANCE_READ",
        "ATTENDANCE_MANAGE",
        "WORK_READ",
        "WORK_CREATE",
        "ABSENCE_READ",
        "ABSENCE_MANAGE",
        "REPORTS_READ",
        "REPORTS_GENERATE",
      ],
    },
  },
  "subcounty.officer@nairobi.go.ke": {
    password: "Officer@Kibra2026!Ops",
    session: {
      user: {
        id: "user_sub_01",
        email: "subcounty.officer@nairobi.go.ke",
        displayName: "Kibra Sub-County Environment Officer",
        mustChangePassword: false,
        assignments: [
          {
            id: "asgn_sub_01",
            role: "SUBCOUNTY_REVIEWER",
            roleName: "Sub-County Environment Officer",
            scopeType: "SUBCOUNTY",
            countyId: "county_nairobi",
            subcountyId: "subcounty_kibra",
            wardId: null,
          },
        ],
      },
      capabilities: [
        "STAFF_READ",
        "ATTENDANCE_READ",
        "WORK_READ",
        "WORK_REVIEW",
        "ABSENCE_READ",
        "ABSENCE_REVIEW",
        "REPORTS_READ",
        "REPORTS_GENERATE",
        "REPORTS_EXPORT",
        "REPORTS_FINALIZE",
        "AUDIT_READ",
      ],
    },
  },
  "director.environment@nairobi.go.ke": {
    password: "Director@Nairobi2026!Ops",
    session: {
      user: {
        id: "user_director_01",
        email: "director.environment@nairobi.go.ke",
        displayName: "Director of Environment",
        mustChangePassword: false,
        assignments: [
          {
            id: "asgn_dir_01",
            role: "DIRECTOR",
            roleName: "Director of Environment",
            scopeType: "COUNTY",
            countyId: "county_nairobi",
            subcountyId: null,
            wardId: null,
          },
        ],
      },
      capabilities: [
        "STAFF_READ",
        "ATTENDANCE_READ",
        "WORK_READ",
        "ABSENCE_READ",
        "REPORTS_READ",
        "REPORTS_GENERATE",
        "REPORTS_EXPORT",
        "REPORTS_FINALIZE",
        "AUDIT_READ",
      ],
    },
  },
};

export const INITIAL_STAFF: Employee[] = [
  {
    id: "staff_01",
    employeeNumber: "ENV-MK-001",
    fullName: "John Otieno Omolo",
    phone: "0712345678",
    email: null,
    designation: "Environmental Field Officer",
    wardId: "ward_makina",
    active: true,
    ward: { id: "ward_makina", code: "MAKINA", name: "Makina" },
    profile: { residence: "Kibra", rosterStatus: "ON_DUTY" },
    assignments: [{ id: "asgn_s1", wardId: "ward_makina" }],
  },
  {
    id: "staff_02",
    employeeNumber: "ENV-MK-002",
    fullName: "Mary Wambui Kamau",
    phone: "0723456789",
    email: null,
    designation: "Environmental Field Officer",
    wardId: "ward_makina",
    active: true,
    ward: { id: "ward_makina", code: "MAKINA", name: "Makina" },
    profile: { residence: "Kibra", rosterStatus: "ON_DUTY" },
    assignments: [{ id: "asgn_s2", wardId: "ward_makina" }],
  },
  {
    id: "staff_03",
    employeeNumber: "ENV-MK-003",
    fullName: "Hassan Ali Mohamed",
    phone: "0734567890",
    email: null,
    designation: "Environmental Field Officer",
    wardId: "ward_makina",
    active: true,
    ward: { id: "ward_makina", code: "MAKINA", name: "Makina" },
    profile: { residence: "Kibra", rosterStatus: "ON_DUTY" },
    assignments: [{ id: "asgn_s3", wardId: "ward_makina" }],
  },
  {
    id: "staff_04",
    employeeNumber: "ENV-MK-004",
    fullName: "Grace Akinyi Ochieng",
    phone: "0745678901",
    email: null,
    designation: "Environmental Field Officer",
    wardId: "ward_makina",
    active: true,
    ward: { id: "ward_makina", code: "MAKINA", name: "Makina" },
    profile: { residence: "Kibra", rosterStatus: "ON_DUTY" },
    assignments: [{ id: "asgn_s4", wardId: "ward_makina" }],
  },
  {
    id: "staff_05",
    employeeNumber: "ENV-MK-005",
    fullName: "Peter Mutua Musyoka",
    phone: "0756789012",
    email: null,
    designation: "Environmental Field Officer",
    wardId: "ward_makina",
    active: true,
    ward: { id: "ward_makina", code: "MAKINA", name: "Makina" },
    profile: { residence: "Kibra", rosterStatus: "ON_DUTY" },
    assignments: [{ id: "asgn_s5", wardId: "ward_makina" }],
  },
];

export const INITIAL_DASHBOARD: DashboardSnapshot = {
  asOf: new Date().toISOString(),
  workDate: new Date().toISOString().slice(0, 10),
  metrics: {
    activeStaff: 48,
    presentOrLateToday: 42,
    openSessions: 1,
    approvedAbsencesToday: 3,
    pendingAbsences: 2,
    pendingWorkLogs: 3,
    finalizedReports: 12,
  },
  queue: [
    {
      type: "WORK_LOG",
      id: "wl_01",
      label: "Drainage Unclogging - Makina Market",
      detail: "Submitted by Makina Ward Officer (5 field personnel assigned)",
      href: "/worklogs",
    },
    {
      type: "ABSENCE",
      id: "abs_01",
      label: "Annual Leave Request - Mary Wambui Kamau",
      detail: "Period: 28 Aug 2026 to 04 Sep 2026 (5 days)",
      href: "/absences",
    },
    {
      type: "WORK_LOG",
      id: "wl_02",
      label: "Litter Collection & Dumpsite Clearance - Olympic Stage",
      detail: "Submitted by Sarang'ombe Ward Officer",
      href: "/worklogs",
    },
  ],
};

export const INITIAL_WORK_LOGS: WorkLog[] = [
  {
    id: "wl_01",
    wardId: "ward_makina",
    workDate: new Date().toISOString().slice(0, 10),
    activity: "Drainage De-silting & Solid Waste Clearance",
    location: "Makina Main Street",
    description:
      "Clearing stormwater drainage conduits along Makina Main Street and evacuating accumulated silt to designated transfer trailers.",
    staffCount: 8,
    challenges: null,
    suggestedSolutions: null,
    truthConfirmed: true,
    status: "SUBMITTED",
    version: 1,
    submittedBy: "Makina Ward Officer",
    reviewedBy: null,
    reviewNote: null,
    createdAt: new Date().toISOString(),
    reviewedAt: null,
    detail: {
      completionStatus: "COMPLETE",
      outstandingWork: null,
    },
    operations: {
      areasRoads: "Makina Main Street",
      numberOfTrips: 4,
      wasteTransferInvolved: true,
      truckId: "KBZ-124X",
      backhoeId: null,
      cleanupDone: true,
      cleanupStakeholders: "Makina Traders Association",
      climateTeamCount: 12,
    },
  },
];

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: "aud_01",
    occurredAt: new Date(Date.now() - 3600000).toISOString(),
    actorUserId: "user_ward_01",
    actorDisplayName: "Makina Ward Environment Officer",
    action: "ATTENDANCE.CHECKIN",
    targetType: "ATTENDANCE_RECORD",
    targetId: "att_01",
    scopeType: "WARD",
    scopeId: "ward_makina",
    sourceIp: "127.0.0.1",
    details: JSON.stringify({ presentCount: 8, ward: "Makina", status: "PRESENT" }),
  },
  {
    id: "aud_02",
    occurredAt: new Date(Date.now() - 7200000).toISOString(),
    actorUserId: "user_ward_01",
    actorDisplayName: "Makina Ward Environment Officer",
    action: "WORK_LOG.SUBMIT",
    targetType: "WORK_LOG",
    targetId: "wl_01",
    scopeType: "WARD",
    scopeId: "ward_makina",
    sourceIp: "127.0.0.1",
    details: JSON.stringify({ title: "Drainage De-silting", evidencePhotos: 3 }),
  },
  {
    id: "aud_03",
    occurredAt: new Date(Date.now() - 14400000).toISOString(),
    actorUserId: "user_admin_01",
    actorDisplayName: "Nairobi System Administrator",
    action: "ACCESS_REQUEST.APPROVED",
    targetType: "USER",
    targetId: "user_ward_01",
    scopeType: "COUNTY",
    scopeId: "county_nairobi",
    sourceIp: "127.0.0.1",
    details: JSON.stringify({ assignedRole: "WARD_OFFICER", ward: "Makina" }),
  },
];

export const INITIAL_USERS: ManagedUser[] = [
  {
    id: "user_admin_01",
    email: "admin@nairobi.go.ke",
    displayName: "Nairobi System Administrator",
    active: true,
    mustChangePassword: false,
    assignments: [
      {
        id: "asgn_admin_01",
        roleCode: "SYSTEM_ADMIN",
        roleName: "System Administrator",
        scopeType: "COUNTY",
        scopeId: "county_nairobi",
      },
    ],
  },
  {
    id: "user_ward_01",
    email: "ward.officer@nairobi.go.ke",
    displayName: "Makina Ward Environment Officer",
    active: true,
    mustChangePassword: false,
    assignments: [
      {
        id: "asgn_ward_01",
        roleCode: "WARD_OFFICER",
        roleName: "Ward Environment Officer",
        scopeType: "WARD",
        scopeId: "ward_makina",
      },
    ],
  },
  {
    id: "user_sub_01",
    email: "subcounty.officer@nairobi.go.ke",
    displayName: "Kibra Sub-County Environment Officer",
    active: true,
    mustChangePassword: false,
    assignments: [
      {
        id: "asgn_sub_01",
        roleCode: "SUBCOUNTY_REVIEWER",
        roleName: "Sub-County Environment Officer",
        scopeType: "SUBCOUNTY",
        scopeId: "subcounty_kibra",
      },
    ],
  },
  {
    id: "user_director_01",
    email: "director.environment@nairobi.go.ke",
    displayName: "Director of Environment",
    active: true,
    mustChangePassword: false,
    assignments: [
      {
        id: "asgn_dir_01",
        roleCode: "DIRECTOR",
        roleName: "Director of Environment",
        scopeType: "COUNTY",
        scopeId: "county_nairobi",
      },
    ],
  },
];

export const INITIAL_PERMISSION_CATALOG: PermissionCatalog = {
  capabilities: [
    { code: "STAFF_READ", name: "View staff register" },
    { code: "STAFF_MANAGE", name: "Manage staff records" },
    { code: "STAFF_IMPORT", name: "Import bulk staff roster" },
    { code: "ATTENDANCE_READ", name: "View attendance records" },
    { code: "ATTENDANCE_MANAGE", name: "Record daily attendance check-ins" },
    { code: "WORK_READ", name: "View field work logs" },
    { code: "WORK_CREATE", name: "Create & submit work logs with evidence" },
    { code: "WORK_REVIEW", name: "Approve or reject work logs" },
    { code: "ABSENCE_READ", name: "View leave & absence requests" },
    { code: "ABSENCE_MANAGE", name: "Submit absence records" },
    { code: "ABSENCE_REVIEW", name: "Review & authorize leave requests" },
    { code: "REPORTS_READ", name: "View operational reports" },
    { code: "REPORTS_GENERATE", name: "Generate draft report snapshots" },
    { code: "REPORTS_EXPORT", name: "Export reports to CSV & PDF" },
    { code: "REPORTS_FINALIZE", name: "Finalize & sign executive reports" },
    { code: "AUDIT_READ", name: "Inspect immutable system audit trail" },
    { code: "USERS_MANAGE", name: "Manage officer accounts & assignments" },
    { code: "PERMISSIONS_MANAGE", name: "Configure role capabilities" },
  ],
  roles: [
    {
      code: "SYSTEM_ADMIN",
      name: "System Administrator",
      capabilities: [
        "STAFF_READ",
        "STAFF_MANAGE",
        "STAFF_IMPORT",
        "ATTENDANCE_READ",
        "ATTENDANCE_MANAGE",
        "WORK_READ",
        "WORK_CREATE",
        "WORK_REVIEW",
        "ABSENCE_READ",
        "ABSENCE_MANAGE",
        "ABSENCE_REVIEW",
        "REPORTS_READ",
        "REPORTS_GENERATE",
        "REPORTS_EXPORT",
        "REPORTS_FINALIZE",
        "AUDIT_READ",
        "USERS_MANAGE",
        "PERMISSIONS_MANAGE",
      ],
    },
    {
      code: "WARD_OFFICER",
      name: "Ward Environment Officer",
      capabilities: [
        "STAFF_READ",
        "STAFF_MANAGE",
        "STAFF_IMPORT",
        "ATTENDANCE_READ",
        "ATTENDANCE_MANAGE",
        "WORK_READ",
        "WORK_CREATE",
        "ABSENCE_READ",
        "ABSENCE_MANAGE",
        "REPORTS_READ",
        "REPORTS_GENERATE",
      ],
    },
    {
      code: "SUBCOUNTY_REVIEWER",
      name: "Sub-County Environment Officer",
      capabilities: [
        "STAFF_READ",
        "ATTENDANCE_READ",
        "WORK_READ",
        "WORK_REVIEW",
        "ABSENCE_READ",
        "ABSENCE_REVIEW",
        "REPORTS_READ",
        "REPORTS_GENERATE",
        "REPORTS_EXPORT",
        "REPORTS_FINALIZE",
        "AUDIT_READ",
      ],
    },
    {
      code: "DIRECTOR",
      name: "Director of Environment",
      capabilities: [
        "STAFF_READ",
        "ATTENDANCE_READ",
        "WORK_READ",
        "ABSENCE_READ",
        "REPORTS_READ",
        "REPORTS_GENERATE",
        "REPORTS_EXPORT",
        "REPORTS_FINALIZE",
        "AUDIT_READ",
      ],
    },
    {
      code: "READ_ONLY",
      name: "Read-Only Observer",
      capabilities: ["ATTENDANCE_READ", "REPORTS_READ", "WORK_READ"],
    },
  ],
};
